# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 59f70a8da3ce01b4dd999f6400f300b951ef1177c82e3b9b195c4cece55944042748a70772309e39a408f5a8b189717c0343f81ccfa253ccb0818972d0ca1345

test:
  secret_key_base: 3116e66ae62c5b918d3f8e9310cc18431276a2b246c8922f2af2c92df9f360fa39d76aea43172e200a0ca4655a96211ec4de3c4da22d9b25aed6837f36cd5b92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
